---
# Install AWS CLI.
- name: Install AWS CLI.
  pip:
    name: awscli
    state: present
  become: true

# Make sure the .aws directory exists for each user.
- name: Create ~/.aws directory
   file:
    path: "{{ item.home }}/{{ item.name }}/.aws"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    state: directory
    force: "no"
  with_items: "{{ aws_users | default([]) }}"
  become: true

# Create config file if not exists.
- name: Create AWS CLI config file
  template:
    src: "{{ aws_config }}"
    dest: "{{ item.home }}/{{ item.name }}/.aws/config"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    force: "yes"
  with_items: "{{ aws_users | default([]) }}"
  become: true

# Copy in a sample credentials file if none exists.
- name: Create AWS CLI credentials file
  template:
    src: "{{ aws_credentials }}"
    dest: "{{ item.home }}/{{ item.name }}/.aws/credentials"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    force: "yes"
  with_items: "{{ aws_users | default([]) }}"
  become: true
