---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-aws-cli

  vars:
    aws_users:
      - name: "jenkins"
        group: "jenkins"
        region: "us-east-1"
        output: "json"
        home: "/var/lib"
    aws_access_key_id: "molecule-aws-access-key-id"
    aws_secret_access_key: "molecule-aws-secret-access-key"
